name: UHCRemastered
version: ${project.version}
main: de.alphahelix.uhcremastered.UHC
authors: [AlphaHelix]
description: A remastered version of UHC / UHC-Remake
website: https://alphahelixdev.github.io
